[project]
name = "geoid_db"
version = "0.1.0"
description = "GeoID database API."
dependencies = [
  "sqlalchemy",
  "pymysql",
  "flask",
  "flasgger",
  "python-dotenv"
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"