swagger: '2.0'
info:
  title: 'GeoID Database API'
  description: 'Simple database API for queries created by GeoID (geoid-bigdata).'
  version: '0.1.0'

definitions:
  Place:
    type: object
    properties:
      id:
        type: integer
        minimum: 1
        example: 1
      location_name:
        type: string
        example: 'Institut Teknologi Bandung'
      location_type:
        type: string
        example: 'Universitas Negeri'
      location_link:
        type: string
        format: url
        example: 'http://127.0.0.1:5000/queries'
      latitude:
        type: number
        format: double
        example: -6.89148
      longitude:
        type: number
        format: double
        example: 107.6106591
      province_id:
        type: integer
        example: 32
      province_name:
        type: string
        example: 'Jawa Barat'
      city_id:
        type: integer
        example: 3273
      city_name:
        type: string
        example: 'Kota Bandung'
      district_id:
        type: integer
        example: 327302
      district_name:
        type: string
        example: 'Coblong'
      village_id:
        type: integer
        format: int64
        example: 3273021006
      village_name:
        type: string
        example: 'Lebak Siliwangi'
      postal_code:
        type: integer
        example: 40132
      rating:
        type: number
        format: float
        example: 4.7
      reviews:
        type: integer
        example: 5000
      description:
        type: string
        example: 'Jl. Ganesa No.10, Lb. Siliwangi, Kecamatan Coblong, Kota Bandung, Jawa Barat 40132'
      query_id:
        type: integer
        minimum: 1
        example: 1
  Queries:
    type: object
    properties:
      id:
        type: integer
        minimum: 1
        example: 1
      term:
        type: string
        example: 'kampus'
      location:
        type: string
        example: 'kota bandung'
      keyword:
        type: string
        example: 'kampus kota bandung'
      lang:
        type: string
        example: 'id'
      timestamp:
        type: integer
        format: int64
        minimum: 0
        example: 1688360400
  PlaceInput:
    allOf:
    - $ref: '#/definitions/Place'
    - type: object  
      required:
      - location_name
      - location_link
      - latitude
      - longitude
  QueriesInput:
    allOf:
    - $ref: '#/definitions/Queries'
    - type: object
      required:
      - keyword
      - lang
      - timestamp
      properties:
        results:
          type: array
          items:
            $ref: '#/definitions/PlaceInput'
  QueriesData:
    type: array
    items:
      $ref: '#/definitions/QueriesInput'
  Content:
    type: object
    properties:
      _links:
        type: object
        properties:
          self:
            type: object
            properties:
              href:
                type: string
                format: url
                example: '/queries'
  ContentPaged:
    type: object
    properties:
      _links:
        type: object
        properties:
          self:
            type: object
            properties:
              href:
                type: string
                format: url
                example: '/queries?limit=10&start=10'
          prev:
            type: object
            properties:
              href:
                type: string
                format: url
                example: '/queries?limit=10&start=0'
          next:
            type: object
            properties:
              href:
                type: string
                format: url
                example: '/queries?limit=10&start=20'
      limit:
        type: integer
        minimum: 1
        default: 10
        example: 10
      start:
        type: integer
        minimum: 0
        default: 0
        example: 0
      size:
        type: integer
        minimum: 0
        example: 1
  Error:
    type: object
    properties:
      error:
        type: object
        properties:
          code:
            type: integer
            example: 404
          name:
            type: string
            example: 'Not Found'
          description:
            type: string
            example: 'Description of the error.'