CREATE TABLE IF NOT EXISTS `queries` (
  `%(_QUERY_ID)s` INT AUTO_INCREMENT,
  `%(_QUERY_TERM)s` VARCHAR(127) NOT NULL,
  `%(_QUERY_LOCATION)s` VARCHAR(127) NOT NULL,
  `%(_QUERY_KEYWORD)s` VARCHAR(255) NOT NULL,
  `%(_QUERY_LANG)s` CHAR(2) NOT NULL,
  `%(_QUERY_TIMESTAMP)s` BIGINT NOT NULL
  PRIMARY KEY (`%(_QUERY_ID)s`),
  KEY (`%(_QUERY_TERM)s`),
  KEY (`%(_QUERY_LOCATION)s`),
  SPATIAL KEY (`%(_COORDINATES)s`)
);
CREATE TABLE IF NOT EXISTS `results` (,
  `%(_RESULT_ID)s` INT AUTO_INCREMENT,
  `%(_QUERY_ID)s` INT NOT NULL,
  `%(_LOCATION_NAME)s` TEXT NOT NULL,
  `%(_LOCATION_TYPE)s` VARCHAR(255),
  `%(_COORDINATES)s` POINT SRID 4326 NOT NULL,
  `%(_PROVINCE_ID)s` INT,
  `%(_PROVINCE_NAME)s` VARCHAR(255),
  `%(_CITY_ID)s` INT,
  `%(_CITY_NAME)s` VARCHAR(255),
  `%(_DISTRICT_ID)s` INT,
  `%(_DISTRICT_NAME)s` VARCHAR(255),
  `%(_VILLAGE_ID)s` BIGINT,
  `%(_VILLAGE_NAME)s` VARCHAR(255),
  `%(_POSTAL_CODE)s` INT,
  `%(_RATING)s` DECIMAL(2,1),
  `%(_REVIEWS)s` INT,
  `%(_DESCRIPTION)s` TEXT CHARACTER SET utf8mb4,
  `%(_LOCATION_LINK)s` TEXT,
  PRIMARY KEY (`%(_RESULTS_ID)s`),
  FOREIGN KEY (`%(_QUERY_ID)s`)
    REFERENCES `queries`(`%(_QUERY_ID)s`)
    ON DELETE CASCADE
)